"""
sdes_file_server.py
Server side of Task 2 (S-DES whole-file exchange).

Flow:
    i.  Receives a (large, e.g. 1 MB) file that the client encrypted
        with S-DES, decrypts it, and displays both the ciphertext and
        the recovered plaintext (previews, since a whole file is too
        big to dump to a terminal).
    ii. Sends a (smaller, e.g. 10 KB) file of its own back to the
        client, encrypted with S-DES using the same key, and displays
        both its plaintext and the ciphertext it is sending.
"""

import socket
import os
import time

import ciphers
from file_transfer import send_bytes, recv_bytes, send_str, recv_str, preview_hex, preview_text

HOST = "127.0.0.1"
PORT = 65433

RECEIVED_FILE = "server_received_plaintext.bin"
SERVER_TO_CLIENT_FILE = "sample_10kb.bin"
SERVER_TO_CLIENT_SIZE = 10 * 1024  # 10 KB


def ensure_sample_file(path: str, size_bytes: int):
    """Create a readable filler file of an exact size if it doesn't exist,
    so the demo works out of the box without the user supplying files."""
    if os.path.exists(path) and os.path.getsize(path) == size_bytes:
        return
    filler = (b"This is a sample file generated by the server for the "
              b"S-DES file-transfer demo. ")
    data = (filler * (size_bytes // len(filler) + 1))[:size_bytes]
    with open(path, "wb") as f:
        f.write(data)
    print(f"[SERVER] Generated sample file '{path}' ({size_bytes} bytes).")


def main():
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        s.bind((HOST, PORT))
        s.listen(1)
        print(f"[SERVER] Listening on {HOST}:{PORT} ...")
        conn, addr = s.accept()
        with conn:
            print(f"[SERVER] Connected by {addr}")

            key = recv_str(conn)
            print(f"[SERVER] Using S-DES key: {key}")

            # ---- (i) receive the big file, decrypt, display ----
            t0 = time.time()
            ciphertext = recv_bytes(conn)
            recv_time = time.time() - t0
            print(f"\n[SERVER] Received {len(ciphertext)} bytes "
                  f"({len(ciphertext)/1024:.1f} KB) in {recv_time:.3f}s")

            t0 = time.time()
            plaintext = ciphers.sdes_decrypt_bytes(ciphertext, key)
            dec_time = time.time() - t0

            with open(RECEIVED_FILE, "wb") as f:
                f.write(plaintext)

            print("\n================ FILE RECEIVED FROM CLIENT (Task 2.i) ================")
            print(f"Size                 : {len(plaintext)} bytes ({len(plaintext)/1024:.1f} KB)")
            print(f"Decryption time      : {dec_time:.3f}s")
            print(f"Ciphertext (hex, first bytes) : {preview_hex(ciphertext)}")
            print(f"Plaintext  (first bytes)      : {preview_text(plaintext)}")
            print(f"Full decrypted file saved to  : {RECEIVED_FILE}")
            print("========================================================================\n")

            # ---- (ii) send our own smaller file back, encrypted ----
            ensure_sample_file(SERVER_TO_CLIENT_FILE, SERVER_TO_CLIENT_SIZE)
            with open(SERVER_TO_CLIENT_FILE, "rb") as f:
                server_plaintext = f.read()

            t0 = time.time()
            server_ciphertext = ciphers.sdes_encrypt_bytes(server_plaintext, key)
            enc_time = time.time() - t0

            print("================ FILE SERVER IS SENDING (Task 2.ii) ==================")
            print(f"Size                          : {len(server_plaintext)} bytes "
                  f"({len(server_plaintext)/1024:.1f} KB)")
            print(f"Encryption time               : {enc_time:.3f}s")
            print(f"Plaintext  (first bytes)      : {preview_text(server_plaintext)}")
            print(f"Ciphertext (hex, first bytes) : {preview_hex(server_ciphertext)}")
            print("========================================================================\n")

            send_bytes(conn, server_ciphertext)
            print("[SERVER] Sent encrypted file to client. Done.")


if __name__ == "__main__":
    main()
