"""
sdes_file_client.py
Client side of Task 2 (S-DES whole-file exchange).

Flow:
    i.  Encrypts a (large, e.g. 1 MB) file locally with S-DES, displays
        both plaintext and ciphertext (previews), and sends the
        encrypted bytes to the server.
    ii. Receives a (smaller, e.g. 10 KB) file back from the server,
        already S-DES-encrypted, decrypts it locally, and displays both
        the ciphertext received and the recovered plaintext.
"""

import socket
import os
import time

import ciphers
from file_transfer import send_bytes, recv_bytes, send_str, preview_hex, preview_text

HOST = "127.0.0.1"
PORT = 65433

CLIENT_TO_SERVER_FILE = "sample_1mb.bin"
CLIENT_TO_SERVER_SIZE = 1024 * 1024  # 1 MB
RECEIVED_FILE = "client_received_plaintext.bin"


def ensure_sample_file(path: str, size_bytes: int):
    """Create a readable filler file of an exact size if it doesn't exist,
    so the demo works out of the box without the user supplying files."""
    if os.path.exists(path) and os.path.getsize(path) == size_bytes:
        return
    filler = (b"This is a sample file generated by the client for the "
              b"S-DES file-transfer demo. ")
    data = (filler * (size_bytes // len(filler) + 1))[:size_bytes]
    with open(path, "wb") as f:
        f.write(data)
    print(f"[CLIENT] Generated sample file '{path}' ({size_bytes} bytes).")


def ask_valid_key() -> str:
    while True:
        key = input("Enter 10-bit S-DES key (e.g. 1010000010): ").strip()
        if len(key) == 10 and set(key) <= {"0", "1"}:
            return key
        print(f"[CLIENT] '{key}' is not a valid key — it must be exactly "
              f"10 characters, each either 0 or 1. Try again.")


def main():
    key = ask_valid_key()

    path = input(
        f"Path to the ~1 MB file to send [Enter for auto-generated "
        f"'{CLIENT_TO_SERVER_FILE}']: "
    ).strip()
    if not path:
        path = CLIENT_TO_SERVER_FILE
    if not os.path.exists(path):
        print(f"[CLIENT] '{path}' doesn't exist yet — generating a sample file there.")
        ensure_sample_file(path, CLIENT_TO_SERVER_SIZE)

    with open(path, "rb") as f:
        plaintext = f.read()

    # ---- (i) encrypt locally and display ----
    t0 = time.time()
    ciphertext = ciphers.sdes_encrypt_bytes(plaintext, key)
    enc_time = time.time() - t0

    print("\n================ FILE CLIENT IS SENDING (Task 2.i) ===================")
    print(f"File                          : {path}")
    print(f"Size                          : {len(plaintext)} bytes ({len(plaintext)/1024:.1f} KB)")
    print(f"Encryption time               : {enc_time:.3f}s")
    print(f"Plaintext  (first bytes)      : {preview_text(plaintext)}")
    print(f"Ciphertext (hex, first bytes) : {preview_hex(ciphertext)}")
    print("========================================================================\n")

    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.connect((HOST, PORT))
        send_str(s, key)

        t0 = time.time()
        send_bytes(s, ciphertext)
        send_time = time.time() - t0
        print(f"[CLIENT] Sent {len(ciphertext)} bytes to server in {send_time:.3f}s")

        # ---- (ii) receive server's smaller file, decrypt, display ----
        server_ciphertext = recv_bytes(s)
        t0 = time.time()
        server_plaintext = ciphers.sdes_decrypt_bytes(server_ciphertext, key)
        dec_time = time.time() - t0

        with open(RECEIVED_FILE, "wb") as f:
            f.write(server_plaintext)

        print("\n================ FILE RECEIVED FROM SERVER (Task 2.ii) ===============")
        print(f"Size                          : {len(server_plaintext)} bytes "
              f"({len(server_plaintext)/1024:.1f} KB)")
        print(f"Decryption time               : {dec_time:.3f}s")
        print(f"Ciphertext (hex, first bytes) : {preview_hex(server_ciphertext)}")
        print(f"Plaintext  (first bytes)      : {preview_text(server_plaintext)}")
        print(f"Full decrypted file saved to  : {RECEIVED_FILE}")
        print("========================================================================\n")


if __name__ == "__main__":
    main()